apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app1
spec:
  selector:
    matchLabels:
      app: demo-app1
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-app1
    spec:
      containers:
      - name: demo-app1
        image: nginx
        ports:
        - containerPort: 8080
